# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    tags:
      - '1.*.*'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      #run: mvn -B package --file ./server/pom.xml
      run: mvn -B clean package spring-boot:repackage --file ./server/pom.xml

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-${{ env.RELEASE_VERSION }}
        path: | 
          ./server/target/webapp-insecure-1.0-SNAPSHOT.jar

    # Create Release v1
    - name: Make Release
      uses: softprops/action-gh-release@v0.1.5
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: release-${{ env.RELEASE_VERSION }}
        files: |
          ./server/target/webapp-insecure-1.0-SNAPSHOT.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}